services:
  melspec-worker:
    build: .
    container_name: melspec-mp-worker
    deploy:
      resources:
        limits:
          # cpus: 4
          memory: 6G
        reservations:
          # cpus: 3.5
          memory: 5G
    env_file:
      - .env
    networks:
      - melspec-inet
    volumes:
      # Must be absolute (Linux example)
      - /home/user/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
      # Must be absolute (Windows example)
      # - "C:/users/User/bla bla/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro"
      
      # Linux example
      - /home/user/Documents/projects/path/to/rawfiles:/app/raw-audio:ro
      # Windows example
      # - C:/Users/user/Documents/path/to/rawfiles:/app/raw-audio:ro

      # Linux example, Windows is like the above
      - /path/to/autotagging_moodtheme-train_clean.csv:/app/autotagging_moodtheme-train_clean.csv:ro
      - /path/to/autotagging_moodtheme-validation_clean.csv:/app/autotagging_moodtheme-validation_clean.csv:ro
      - /path/to/autotagging_moodtheme-test_clean.csv:/app/autotagging_moodtheme-test_clean.csv:ro


networks:
  melspec-inet:
    name: melspec-inet
